[package]
name = "clipboard-google-translate"
version = "0.1.0"
authors = ["YoungJoo Lee <youngker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.2"
url = "*"
hyper = "0.12.35"
clipboard = "0.5.0"
regex = "1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
glfw = "0.33.0"
imgui = "0.2.1"
imgui-opengl-renderer = "0.6.0"
gl = "*"
log = "0.4.6"
env_logger = { version = "0.6.2", default-features = false, features = ["termcolor"] }
